server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    properties:
        hibernate:
          format_sql: true

    hibernate:
      ddl-auto: create

    database-paltform: org.hibernate.dialect.H2Dialect

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: debug
    com.kakaopay.payments.api: debug
